### PR TITLE
Website

### PR DESCRIPTION
**Pull request by LadyBluenotes**
#1 - This PR is for the website revamp.

### CODE REVIEW

**Comment by LadyBluenotes** [comment]
@Sulstice 

Could you take a look at this? 

There's a few things about it so far:

1. Not a lot of copy was written - unsure of if I'm on the write path so I kept it Lorem for the time being.
2. I have some blank spaces saved for photos - so if you could find 2, that'd be great. 
3. Globe has been a headache - currently just have a picture in the place to show where it will be going.
4. Contributor section isn't mobile friendly yet. Intention is to have people in the relevant categories show up based on the role they have with the organization. I've split them into 4 for the time being, any more than that could be a quite a bit crowded.
5. Wasn't sure what was wanted for the "open source positions" part, so I kept it generic for the time being.

I could send a separate PR for the website we want for Thursday. I don't see it being entirely done by then (the people and their roles will require some JS to be written and I don't think I can get that done before then due to my work).

I've written this all in HTML with Tailwind. I could get it all done by Thursday if you're good with me writing it in React (where I keep it a single page, just separate the components into their files). I do understand you wanting me to keep it simple with HTML, however, so I'm good either way.

Let me know what you think!

**Comment by Sulstice** [comment]
@LadyBluenotes Let's delay the website so we can build it with clarity. It's too much work for short amount of time. I don't want to stress us out on an arbitrary deadline if it's not feasible. 

We could wipe the whole thing and move over to reactjs. Do you want me to give the GlobeJS thing a shot to see if I can get it all running that way you can work on the components and maybe I can figure out a way to integrate that with yours? 

I saw you change the index over into tailwind css. I'm running the index.html from the root directory but it looks like the same site. Am I missing something?

**Comment by LadyBluenotes** [comment]
@Sulstice I'll move everything over to Next.js and try seeing if i can get the globe working there before getting you to give it a shot. 

I'll probably have to make a new PR - I'll make a branch through the main repo vs my own fork to make it easier going forward.

**Comment by LadyBluenotes** [comment]
Closing because we changed branches

**Pull request closed without merging**
